### ISSUE TITLE
Redeploying lingo causes deployments to get lost

### ISSUE THREAD

**Issue by samos123** [substratusai/lingo#30]
Steps to reproduce:
1. `helm install lingo substratusai/lingo`
2. Install a deployment to be used with lingo:
```
helm upgrade --install stapi-minilm-l6-v2 substratusai/stapi -f - << EOF
model: all-MiniLM-L6-v2
replicaCount: 0
deploymentAnnotations:
  lingo.substratus.ai/models: text-embedding-ada-002
EOF
```
3. Re-install lingo: `helm uninstall lingo && helm install lingo substratusai/lingo`

Current result:
Lingo will no longer be able to list and scale stapi deployment even though it's still there

Expected result:
Lingo should still work on all existing deployments even after a re-install

**Comment by nstogner** [comment]
I thought I reproduced this by watching the logs and not initially seeing mention of stapi. However after starting a new port-forward and sending a new request, lingo scaled up the stapi deployment after re-install of lingo.

**Comment by samos123** [comment]
I can't reproduce either. Closing
