### ISSUE TITLE
Fine tuning backend limits

### ISSUE THREAD

**Issue by alpe** [substratusai/lingo#41]
Similar to #12 other configurations (annotation) may be helpful on the deployment level:
* absolute max instances that can be created - to limit resources 
* max queue size per instance - to fail fast on high load

**Comment by nstogner** [comment]
* Bullet point 1 might be better supported using [ResourceQuotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/).
* Bullet point 2 is supported here: https://github.com/substratusai/lingo/blob/bc4ba0df53feb27e7b10923008b2d25ef985807b/pkg/deployments/manager.go#L99

**Comment by alpe** [comment]
Nice!
