### ISSUE TITLE
add /healthz endpoint that responds 200 OK

### ISSUE THREAD

**Issue by samos123** [substratusai/lingo#5]

**Comment by alpe** [comment]
Can you specify the conditions and usage for the endpoint, please?
K8s supports `liveness` and `readiness` probes.  Both can also be checked via [tcp](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe).
Do I assume correct that lingo is ready to serve on startup and alive when listening on the proxy port?

**Comment by alpe** [comment]
🤔 I think it is fair to wait for one reconcile run of the deployments manager to return `ready`. Otherwise requests will fail with `404` on this new instance.
