### ISSUE TITLE
Customizable codebase

### ISSUE THREAD

**Issue by nstogner** [substratusai/lingo#63]
Some users would like to use Lingo but need slightly different behavior. It would be good to consider how to design the codebase in such a manner as to allow for maximum extensibility while keeping it as simple and maintainable as possible.

**Comment by nstogner** [comment]
I am thinking this is something that we probably want to add into the non-goals list. If we design Lingo to be used as a library we should consider our packages as the interface for a portion of our user base. Versioning and maintaining backwards compatibility of a library is much more constrained than doing so at the boundary of a deployable program.

**Comment by samos123** [comment]
I agree that it's not worth the additional effort right now. This may change once more users demand this.
