### ISSUE TITLE
CNCF TAG-Runtime or/and CNCF Cloud Native WG discussion

### ISSUE THREAD

**Issue by raravena80** [substratusai/lingo#84]
Hello lingo team,

I'm one of the co-chairs of the CNCF TAG-Runtime, I think it would be great for you to present/discuss the project in one of our meetings. For example, discuss things such as adoption, architecture, etc.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by samos123** [comment]
I've added us to the agenda for April 4th. Thanks for reaching out!

**Comment by raravena80** [comment]
Thanks @samos123, looking forward!
