### ISSUE TITLE
Handling stale requests: Cancelling the request never clears up the replica count 

### ISSUE THREAD

**Issue by samos123** [substratusai/lingo#9]
Steps to reproduce:
1. Run curl to trigger scale from 0
2. Cancel the curl
3. Watch the pod scale up and have an error at runtime, the pod will retry will forever

Expected result:
After configurable x minutes with default being 30 minutes, any still pending requests should get cleared automatically and cause scale down

**Comment by nstogner** [comment]
Trying to reproduce:

1. `curl`'d lingo
2. Ctrl-C'd `curl`
3. Saw backend pod scale up
4. Saw backend pod eventually scale down to 0

Curious why the Pod had a runtime error in your case? Are you referring to the model server pod or lingo itself?

**Comment by nstogner** [comment]
#10 might help diagnose this.

**Comment by samos123** [comment]
in my case the vLLM server pod had a runtime error so it would never come up. Eventually I deleted it but seems it kept on trying to scale up indefinitely. I confirm that I can't reproduce by just Ctrl + C.

**Comment by samos123** [comment]
Closing for now, unless I can reproduce
